import type { Metadata } from "next"
import { Press_Start_2P } from "next/font/google"
import "./globals.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const press = Press_Start_2P({ subsets: ["latin"], variable: '--font-press-start-2p',
	  weight: "400", display: "swap" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={press.className}>
        {children}
      </body>
    </html>
  )
}
